# GWS 2022 Analysis

In [8]:
import sqlite3
import pandas as pd

### Connecting to database

In [9]:
db_path = "data/nba.sqlite"  # change to your path
conn = sqlite3.connect(db_path)

tables = conn.execute("SELECT name FROM sqlite_master WHERE type='table';").fetchall()
print([t[0] for t in tables])

['game', 'game_summary', 'other_stats', 'officials', 'inactive_players', 'game_info', 'line_score', 'play_by_play', 'player', 'team', 'common_player_info', 'team_details', 'team_history', 'draft_combine_stats', 'draft_history', 'team_info_common']

### Retreiving data
Getting both home and away game for the 2022 season

In [10]:
query = """
SELECT *
FROM game as g
JOIN other_stats AS o ON g.game_id = o.game_id
JOIN game_info as i ON g.game_id = i.game_id
WHERE g.team_abbreviation_home LIKE "%GSW%"
AND g.season_id = "22021"
"""
df_home = pd.read_sql_query(query, conn)
df_home.head()

,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,fgm_home,...,pts_fb_away,largest_lead_away,team_turnovers_away,total_turnovers_away,team_rebounds_away,pts_off_to_away,game_id,game_date,attendance,game_time
0,22021,1610612744,GSW,Golden State Warriors,0022100016,2021-10-21 00:00:00,GSW vs. LAC,W,240,43.0,...,25,18,0,21,9,18,0022100016,2021-10-21 00:00:00,18064,2:28
1,22021,1610612744,GSW,Golden State Warriors,0022100086,2021-10-30 00:00:00,GSW vs. OKC,W,240,39.0,...,16,0,1,16,10,12,0022100086,2021-10-30 00:00:00,18064,2:02
2,22021,1610612744,GSW,Golden State Warriors,0022100117,2021-11-03 00:00:00,GSW vs. CHA,W,240,42.0,...,19,22,1,17,6,17,0022100117,2021-11-03 00:00:00,18064,2:15
3,22021,1610612744,GSW,Golden State Warriors,0022100130,2021-11-05 00:00:00,GSW vs. NOP,W,240,47.0,...,11,7,2,19,10,26,0022100130,2021-11-05 00:00:00,18064,2:13
4,22021,1610612744,GSW,Golden State Warriors,0022100145,2021-11-07 00:00:00,GSW vs. HOU,W,240,44.0,...,36,21,2,17,7,28,0022100145,2021-11-07 00:00:00,18064,2:12

In [11]:
query = """
SELECT *
FROM game AS g
JOIN other_stats AS o ON g.game_id = o.game_id
JOIN game_info as i ON g.game_id = i.game_id
WHERE matchup_home LIKE "%GSW%"
    AND g.season_id = "22021"
    AND g.team_abbreviation_home NOT LIKE "%GSW%"

"""
df_away = pd.read_sql_query(query, conn)
df_away.head()

,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,fgm_home,...,pts_fb_away,largest_lead_away,team_turnovers_away,total_turnovers_away,team_rebounds_away,pts_off_to_away,game_id,game_date,attendance,game_time
0,22021,1610612747,LAL,Los Angeles Lakers,0022100002,2021-10-19 00:00:00,LAL vs. GSW,L,240,45.0,...,20,10,1,18,13,20,0022100002,2021-10-19 00:00:00,18997,2:33
1,22021,1610612758,SAC,Sacramento Kings,0022100039,2021-10-24 00:00:00,SAC vs. GSW,L,240,42.0,...,16,12,1,7,10,9,0022100039,2021-10-24 00:00:00,13876,2:17
2,22021,1610612760,OKC,Oklahoma City Thunder,0022100051,2021-10-26 00:00:00,OKC vs. GSW,L,240,36.0,...,4,10,0,15,7,18,0022100051,2021-10-26 00:00:00,15717,2:11
3,22021,1610612766,CHA,Charlotte Hornets,0022100194,2021-11-14 00:00:00,CHA vs. GSW,W,240,42.0,...,10,7,2,13,11,17,0022100194,2021-11-14 00:00:00,19559,2:15
4,22021,1610612751,BKN,Brooklyn Nets,0022100210,2021-11-16 00:00:00,BKN vs. GSW,L,240,34.0,...,25,28,1,22,8,20,0022100210,2021-11-16 00:00:00,17732,2:23

### Removing duplicated columns

In [12]:
df_home = df_home.loc[:, ~df_home.columns.duplicated()]
df_away = df_away.loc[:, ~df_away.columns.duplicated()]